name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Lint – rustfmt
        run: cargo fmt --all -- --check

      - name: Lint – clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --all --verbose

      - name: Generate code coverage
        run: cargo tarpaulin --out Lcov

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: lcov.info

      - name: Upload to codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}